name: Windows
on: workflow_dispatch
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-2022
    steps:
      - name: Checkout sdl
        uses: actions/checkout@v4
        with:
          repository: libsdl-org/SDL
          ref: release-2.28.4
          path: sdl
      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build sdl
        run: |
          cd sdl
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Debug
          cmake --install . --config Debug --prefix install/Debug
          cmake --build . --config Release
          cmake --install . --config Release --prefix install/Release
      - name: Generate zip
        run: |
          echo ${{ github.sha }} > Release.txt
          Compress-Archive -Path ./sdl/build/install/*,./Release.txt -DestinationPath sdl.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: sdl.zip